# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pricing.v1 import pricing_pb2 as pricing_dot_v1_dot_pricing__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pricing/v1/pricing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PricingServiceStub(object):
    """A calculation-only service. It owns no positions, orders, or vendor sessions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/sim_hedge.pricing.v1.PricingService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pricing_dot_v1_dot_pricing__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Price = channel.unary_unary(
                '/sim_hedge.pricing.v1.PricingService/Price',
                request_serializer=pricing_dot_v1_dot_pricing__pb2.PriceRequest.SerializeToString,
                response_deserializer=pricing_dot_v1_dot_pricing__pb2.PriceResponse.FromString,
                _registered_method=True)


class PricingServiceServicer(object):
    """A calculation-only service. It owns no positions, orders, or vendor sessions.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Price(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PricingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pricing_dot_v1_dot_pricing__pb2.HealthResponse.SerializeToString,
            ),
            'Price': grpc.unary_unary_rpc_method_handler(
                    servicer.Price,
                    request_deserializer=pricing_dot_v1_dot_pricing__pb2.PriceRequest.FromString,
                    response_serializer=pricing_dot_v1_dot_pricing__pb2.PriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sim_hedge.pricing.v1.PricingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sim_hedge.pricing.v1.PricingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PricingService(object):
    """A calculation-only service. It owns no positions, orders, or vendor sessions.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sim_hedge.pricing.v1.PricingService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pricing_dot_v1_dot_pricing__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sim_hedge.pricing.v1.PricingService/Price',
            pricing_dot_v1_dot_pricing__pb2.PriceRequest.SerializeToString,
            pricing_dot_v1_dot_pricing__pb2.PriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
