# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hedging.v1 import hedging_pb2 as hedging_dot_v1_dot_hedging__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hedging/v1/hedging_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HedgeServiceStub(object):
    """Stateless calculation service. It owns no broker sessions or working orders.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/sim_hedge.hedging.v1.HedgeService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=hedging_dot_v1_dot_hedging__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Propose = channel.unary_unary(
                '/sim_hedge.hedging.v1.HedgeService/Propose',
                request_serializer=hedging_dot_v1_dot_hedging__pb2.HedgeRequest.SerializeToString,
                response_deserializer=hedging_dot_v1_dot_hedging__pb2.HedgeProposal.FromString,
                _registered_method=True)


class HedgeServiceServicer(object):
    """Stateless calculation service. It owns no broker sessions or working orders.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HedgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=hedging_dot_v1_dot_hedging__pb2.HealthResponse.SerializeToString,
            ),
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=hedging_dot_v1_dot_hedging__pb2.HedgeRequest.FromString,
                    response_serializer=hedging_dot_v1_dot_hedging__pb2.HedgeProposal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sim_hedge.hedging.v1.HedgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sim_hedge.hedging.v1.HedgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HedgeService(object):
    """Stateless calculation service. It owns no broker sessions or working orders.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sim_hedge.hedging.v1.HedgeService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            hedging_dot_v1_dot_hedging__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sim_hedge.hedging.v1.HedgeService/Propose',
            hedging_dot_v1_dot_hedging__pb2.HedgeRequest.SerializeToString,
            hedging_dot_v1_dot_hedging__pb2.HedgeProposal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
